[metadata]
name = terminal-manager
version = 0.8.0
description = A portable X11 dashboard for existing terminal windows and shells
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
author = Smashwinny
classifiers =
    Environment :: X11 Applications
    License :: OSI Approved :: MIT License
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3

[options]
packages = find:
python_requires = >=3.9

[options.packages.find]
include = terminal_manager*

[options.entry_points]
console_scripts =
    terminal-manager = terminal_manager.app:main
    terminal-manager-register = terminal_manager.monitor:register_main
    terminal-manager-unregister = terminal_manager.monitor:unregister_main
